name: "Run tests on NodeJS"

on:
  push:
    paths:
      - ".github/workflows/node.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["lts/*", "latest"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 10

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_store_path::$(pnpm store path)"

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        name: Set up pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Build Source
        run: pnpm run --if-present build

      - name: Lint Source
        run: pnpm run --if-present lint

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Tests
        run: pnpm run --if-present test
